var nameList = [
  "Farman Ullah",
  "Kamran Khan",
  "Asad Ullah",
  "Sami Ullah",
  "Ahmed Khan",
  "Hassan Ali",
  "Mohammed Rizwan",
  "Imran Farooq",
  "Usman Ghani",
  "Irfan Haider",
  "Bilal Akhtar",
  "Zahid Mahmood",
  "Zain Ul Abideen",
  "Mujahid Ali",
  "Salman Tariq",
  "Naveed Anwar",
  "Faisal Shah",
  "Noman Ahmad",
  "Rehan Khan",
  "Tariq Javed",
  "Adnan Qureshi",
  "Yasir Arafat",
  "Farooq Ahmed",
  "Ahsan Jamil",
  "Junaid Khan",
  "Shahid Mehmood",
  "Waqar Younis",
  "Fahad Mustafa",
  "Adeel Raza",
  "Kashif Iqbal",
  "Sajjad Ali",
  "Hafiz Abdullah",
  "Arshad Mahmood",
  "Atif Aslam",
  "Saad Saeed",
  "Mubashir Ali",
  "Rafi Ullah",
  "Shafqat Ali",
  "Hamza Malik",
  "Shan Ahmed",
  "Danish Ali",
  "Waqas Khan",
  "Fawad Khan",
  "Taimoor Ali",
  "Babar Azam",
  "Arif Hussain",
  "Naseer Khan",
  "Qasim Raza",
  "Haroon Rashid",
  "Farhan Ali",
  "Shoaib Akhtar",
  "Zubair Khan",
  "Azeem Khan",
  "Rizwan Ahmad",
  "Muzaffar Ali",
  "Khalid Mehmood",
  "Tahir Shah",
  "Wali Ullah",
  "Arif Qureshi",
  "Anwar Ali",
  "Shafiq Ahmed",
  "Riaz Khan",
  "Munir Ahmad",
  "Tanveer Hussain",
];

export const randomName = () => {
  return nameList[Math.floor(Math.random() * nameList.length)];
};

var commentsList = [
  "Informative",
  "Impressive",
  "Very nice",
  "Great job, keep it up",
  "Excellent work",
  "Highly recommended",
  "Well done",
  "Outstanding",
  "Superb",
  "Fantastic",
  "Amazing content",
  "Bravo",
  "Incredible effort",
  "Wonderful",
  "Top-notch",
  "Exceptional",
  "Kudos",
  "Remarkable",
  "Perfect",
  "Inspiring",
  "Terrific",
  "Splendid",
  "Super",
  "Phenomenal",
  "Marvellous",
  "Magnificent",
  "Brilliant",
  "Insightful",
  "Astounding",
  "Outstanding performance",
  "First-class",
  "Quality work",
  "Stunning",
  "Noteworthy",
  "Commendable",
  "A+ effort",
  "Excellent presentation",
  "Well-executed",
  "Awesome",
  "Terrific job",
  "Impressive skills",
  "Thoroughly enjoyed",
  "Keep it coming",
  "Loved it",
  "High-quality",
  "Great explanation",
  "Spot on",
  "Crystal clear",
  "To the point",
  "Well articulated",
  "Thought-provoking",
  "Highly informative",
  "Deeply impressed",
  "Very helpful",
  "Made my day",
  "Truly inspiring",
  "Masterful",
  "Exceptionally good",
  "Hats off",
  "Brilliantly done",
  "Eloquent",
];

export const randomComment = () => {
  return commentsList[Math.floor(Math.random() * commentsList.length)];
};
